- name: Add admin group to sudoers
  lineinfile: dest=/etc/sudoers regexp="^%{{ admin_group }}" line="%infra_admin ALL=(ALL) NOPASSWD:ALL"

- name: Disable Requiretty from sudoers
  lineinfile: dest=/etc/sudoers regexp="Defaults    requiretty" line="#Defaults    requiretty"
